### PR TITLE
Add option not to render the label by the widget

### PR DESCRIPTION
**Pull request by MadAnd**

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Hi @MadAnd thank you very much for your pull request, but why is this better than just setting options label to false?: 

```php 
<?= $form->field($model, 'validated')->widget(SwitchBox::className(),[
   'options' => [
       'label' => false
   ]
    'clientOptions' => [
        'size' => 'large',
        'onColor' => 'success',
        'offColor' => 'danger'
    ]
]);?>
```

**Comment by MadAnd** [comment]
Hi @tonydspaniard ,
my solution is like a handy shorthand, no technical advantage though.

But if you decide not to merge it, please mention your solution in the README, since it was not that obvious (at least for me) at first. Thanks!

**Comment by tonydspaniard** [comment]
Sure, will do. Thanks again!

**Comment by tonydspaniard** [comment]
added: https://github.com/2amigos/yii2-switch-widget/blob/master/README.md 

Thank you again

**Pull request closed without merging**
